const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Mouse,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Behaviors.Flash,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Behaviors.Platform.Cnds.OnFall,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.ScriptsInEvents.Level1events_Event6_Act1,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Y,
		C3.ScriptsInEvents.Level1events_Event7_Act1,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.ScriptsInEvents.Level1events_Event12_Act5,
		C3.Plugins.System.Acts.AddVar,
		C3.ScriptsInEvents.Level1events_Event13_Act5,
		C3.ScriptsInEvents.Level1events_Event17_Act2,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.ScriptsInEvents.Level1events_Event20_Act5,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Cnds.CompareY,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{Mouse: 0},
	{Âncora: 0},
	{fundo1: 0},
	{Sólido: 0},
	{plataforma: 0},
	{lava: 0},
	{lava2: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{jogador: 0},
	{Teclado: 0},
	{vida: 0},
	{Vidas: 0},
	{GameOver: 0},
	{Texto: 0},
	{Senóide: 0},
	{Piscar: 0},
	{Zoombie: 0},
	{FaseUm: 0},
	{FaseDois: 0},
	{plataformaMexe: 0},
	{Nuvem: 0},
	{dragao: 0},
	{Projétil: 0},
	{DestruirForaDoLayout: 0},
	{shuriken: 0},
	{fundoGameOver: 0},
	{JogarNovamente: 0},
	{botaoMenu: 0},
	{fundoTelaInicio: 0},
	{BemVindo: 0},
	{IniciarJogo: 0},
	{VerHistoria: 0},
	{lava3: 0},
	{fundoHistoria: 0},
	{FonteDeSprites: 0},
	{Texto2: 0},
	{Texto3: 0},
	{ComoJogar: 0},
	{back: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Texto4: 0},
	{TeclasMovimento: 0},
	{textoTeclasMovimento: 0},
	{Espaço: 0},
	{textoEspaço: 0},
	{Texto7: 0},
	{textoVidas: 0},
	{Sprite: 0},
	{back2: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{Texto5: 0},
	{Sprite2: 0},
	{Texto6: 0},
	{NuvemSome: 0},
	{Trofeu: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Texto8: 0},
	{FonteDeSprites2: 0},
	{Sprite4: 0},
	{Pontuacao: 0},
	{Áudio: 0},
	{velocidade: 0},
	{alturaPersonagem: 0},
	{Pontos: 0}
];

self.InstanceType = {
	Mouse: class extends self.IInstance {},
	fundo1: class extends self.ITiledBackgroundInstance {},
	plataforma: class extends self.ISpriteInstance {},
	lava: class extends self.ISpriteInstance {},
	lava2: class extends self.ISpriteInstance {},
	jogador: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	vida: class extends self.ISpriteInstance {},
	Vidas: class extends self.ITextInstance {},
	GameOver: class extends self.ITextInstance {},
	Texto: class extends self.ITextInstance {},
	Zoombie: class extends self.ISpriteInstance {},
	FaseUm: class extends self.ITiledBackgroundInstance {},
	FaseDois: class extends self.ITiledBackgroundInstance {},
	plataformaMexe: class extends self.ISpriteInstance {},
	Nuvem: class extends self.ISpriteInstance {},
	dragao: class extends self.ISpriteInstance {},
	shuriken: class extends self.ISpriteInstance {},
	fundoGameOver: class extends self.ITiledBackgroundInstance {},
	JogarNovamente: class extends self.ISpriteInstance {},
	botaoMenu: class extends self.ISpriteInstance {},
	fundoTelaInicio: class extends self.ISpriteInstance {},
	BemVindo: class extends self.ISpriteInstance {},
	IniciarJogo: class extends self.ISpriteInstance {},
	VerHistoria: class extends self.ISpriteInstance {},
	lava3: class extends self.ITiledBackgroundInstance {},
	fundoHistoria: class extends self.ITiledBackgroundInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	ComoJogar: class extends self.ISpriteInstance {},
	back: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Texto4: class extends self.ITextInstance {},
	TeclasMovimento: class extends self.ISpriteInstance {},
	textoTeclasMovimento: class extends self.ITextInstance {},
	Espaço: class extends self.ISpriteInstance {},
	textoEspaço: class extends self.ITextInstance {},
	Texto7: class extends self.ITextInstance {},
	textoVidas: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	back2: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	Texto5: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Texto6: class extends self.ITextInstance {},
	NuvemSome: class extends self.ISpriteInstance {},
	Trofeu: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Texto8: class extends self.ITextInstance {},
	FonteDeSprites2: class extends self.ISpriteFontInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Pontuacao: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {}
}